language: go
os:
- linux
- osx
go:
- 1.10.x
- master
services:
- docker
script:
- make test
deploy:
  provider: script
  script: make release
  on:
    master: true
    tags: true
    condition: "$TRAVIS_GO_VERSION =~ ^1\\.10(\\.[0-9]+)?$ && $TRAVIS_OS_NAME = linux"
env:
  secure: mDWdz+CPsaTZRpGT88V4TH1tY2Sp6J4AJboCqN9sHm6S8FmfGv8efgfsbfa1ct4NO+8hkyXzNztFm+A0BML/q9xc06Q2zqGx4DW4GmmlcK/MCnnanyBuRFCbKqdMvpWFnFgp7muJnDKNHd4RXeTm8e1c3lFJmxmmKHPb0VI9i4f0fDu5IougHCJ8LUFx7gUa0P4OESWH1lF0ogG4cLQ9bfAgG5KvQ8xjv4jY3D4qVAU4rLB24s9/OpgHpuUMXyw3LD3qWfnstz7jbtnkMUmUm1CBKfNdxCHW5IKl28D2gM7uVvPn3kid2eqapN3Qthsbz33yDuoyYp4HxAuXMVf8O9SxqlsRfy+g51YNdyTx6OgZaWGUFi3r9lrwpS4ZP19dtyy8R/r8mDANJUO+zqIpriYYRsZHBKwfz1EXERn24fjybfyo/tqmEUw5FVJj0SINx2nja6YXFAbB95ASOoG1vHDg6t02hHcUn4ZSlSb8Z3ZPBRXIY14zL1JT5ZZwTYOE9/RiFjpM0dYNsCCttutGsbQPivSBt0tQJ/plWarWKtsoVVrpMQGEwamsBqdbT4vJtOQaeivdIM6Q4Oo8ydheGC03OKuxhvGjCHDqK7vlcUYdbfGrCA+dXSHGmOiJlKvRbEm5LATb/6nbxcpoN/bDnGPzlFLAjNcLzw5kRo8a9LU=
